CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(20) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    is_blocked BOOLEAN NOT NULL DEFAULT FALSE,
    role VARCHAR(20) NOT NULL CHECK (role IN ('USER','ADMIN'))
);
CREATE TABLE listings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    description TEXT,
    price NUMERIC(10,2) NOT NULL CHECK (price > 0),
    status VARCHAR(20) NOT NULL CHECK (status IN ('ACTIVE','SOLD','CLOSED')),
    user_id BIGINT NOT NULL REFERENCES users(id),
    category VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL
);
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id BIGINT NOT NULL REFERENCES listings(id),
    buyer_id BIGINT NOT NULL REFERENCES users(id),
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING','CONFIRMED','COMPLETED','CANCELLED')),
    order_date TIMESTAMP NOT NULL
);
CREATE INDEX idx_listings_user_created ON listings(user_id,created_at DESC);
CREATE INDEX idx_orders_listing ON orders(listing_id);
CREATE INDEX idx_orders_buyer_date ON orders(buyer_id,order_date DESC);
CREATE TABLE bootstrap_history (
    name VARCHAR(100) PRIMARY KEY,
    applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
